# Generated by Django 4.0.6 on 2022-08-10 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_infousers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
